### ISSUE TITLE
static background on fullpage pages

### ISSUE THREAD

**Issue by cerokool32** [creativetimofficial/material-dashboard-pro-angular#22]
is there any way to create a fixed fullpage background and make items float over it, like material kit?

**Comment by alexandru-paduraru** [comment]
@cerokool32 yes, you cand do that, please go at the end of material-dashboard.css and add this code:

```css
.full-page .full-page-background{
position: fixed; !important;
}
```

Best,
Alex
