### ISSUE TITLE
Another print error

### ISSUE THREAD

**Issue by ehdwns980416** [creativetimofficial/material-dashboard-pro-angular#223]
I have another print error..please check it..
I want to set print paper size with `@page` in my site.
This is what I did, but not working:
```css
@media print {
  @page {
    size: A4 landscape;
    margin: 0;
  }
}
```
I tried using `!important` to each style, but it's not working too.
What should I do?
